//
//  InvoiceGenerator.swift
//  Tally
//
//  Created by George Clinkscales on 5/28/26.
//

import Foundation
import PDFKit
#if os(iOS)
import UIKit
#else
import AppKit
#endif

struct InvoicePDFGenerator {
    static func generate(
        invoiceNumber: String,
        yourName: String,
        yourEmail: String,
        client: String,
        sessions: [SessionModel],
        hourlyRate: Double,
        notes: String,
        paymentLink: String = ""
    ) async -> URL? {
        let totalHours = sessions.reduce(0) { $0 + $1.hours }
        let totalAmount = totalHours * hourlyRate
        let dateStr = Date().formatted(date: .long, time: .omitted)
        
        let html = """
        <!DOCTYPE html>
        <html>
        <head>
        <style>
            body { font-family: -apple-system, sans-serif; margin: 40px; color: #1a1a1a; }
            .header { display: flex; justify-content: space-between; margin-bottom: 40px; }
            .title { font-size: 36px; font-weight: bold; color: #0055FF; }
            .invoice-info { text-align: right; color: #666; }
            .from-to { display: flex; justify-content: space-between; margin-bottom: 40px; }
            .label { font-size: 12px; color: #666; text-transform: uppercase; margin-bottom: 4px; }
            .value { font-size: 16px; font-weight: 500; }
            table { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
            th { background: #f5f5f5; padding: 12px; text-align: left; font-size: 12px; text-transform: uppercase; color: #666; }
            td { padding: 12px; border-bottom: 1px solid #eee; font-size: 14px; }
            .total-row { font-weight: bold; font-size: 16px; }
            .total-amount { color: #0055FF; font-size: 20px; font-weight: bold; }
            .notes { margin-top: 32px; padding: 16px; background: #f9f9f9; border-radius: 8px; font-size: 14px; color: #666; }
            .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; }
            .pay-btn { display: block; margin: 32px auto; padding: 16px 40px; background: #635BFF; color: white; text-decoration: none; border-radius: 8px; font-size: 18px; font-weight: bold; text-align: center; max-width: 300px; }
        </style>
        </head>
        <body>
        <div class="header">
            <div class="title">INVOICE</div>
            <div class="invoice-info">
                <div>Invoice #\(invoiceNumber)</div>
                <div>\(dateStr)</div>
            </div>
        </div>
        
        <div class="from-to">
            <div>
                <div class="label">From</div>
                <div class="value">\(yourName)</div>
                <div style="color: #666;">\(yourEmail)</div>
            </div>
            <div>
                <div class="label">Bill To</div>
                <div class="value">\(client)</div>
            </div>
        </div>
        
        <table>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Hours</th>
                <th>Rate</th>
                <th>Amount</th>
            </tr>
            \(sessionRows(sessions: sessions, hourlyRate: hourlyRate))
            <tr class="total-row">
                <td colspan="2">Total</td>
                <td>\(TimeFormatter.shortFormat(totalHours))</td>
                <td>\(hourlyRate.formatted(.currency(code: CurrencyPreference.current)))/hr</td>
                <td class="total-amount">\(totalAmount.formatted(.currency(code: CurrencyPreference.current)))</td>
            </tr>
        </table>
        
        \(notes.isEmpty ? "" : "<div class='notes'>\(notes)</div>")

        \(paymentLink.isEmpty ? "" : "<a class='pay-btn' href='\(paymentLink)'>Pay Now \(totalAmount.formatted(.currency(code: CurrencyPreference.current)))</a>")

        <div class="footer">Generated by Tally</div>
        </body>
        </html>
        """
        
        return await MainActor.run {
            generatePDF(from: html, filename: "invoice-\(client)-\(invoiceNumber).pdf")
        }
    }
    
    private static func sessionRows(sessions: [SessionModel], hourlyRate: Double) -> String {
        sessions.map { session in
            let amount = session.hours * hourlyRate
            let note = session.taskNote ?? "Development work"
            return """
            <tr>
                <td>\(session.date ?? "")</td>
                <td>\(note)</td>
                <td>\(TimeFormatter.shortFormat(session.hours))</td>
                <td>\(hourlyRate.formatted(.currency(code: CurrencyPreference.current)))/hr</td>
                <td>\(amount.formatted(.currency(code: CurrencyPreference.current)))</td>
            </tr>
            """
        }.joined()
    }
    
    private static func generatePDF(from html: String, filename: String) -> URL? {
        #if os(iOS)
        let fmt = UIMarkupTextPrintFormatter(markupText: html)
        let render = UIPrintPageRenderer()
        render.addPrintFormatter(fmt, startingAtPageAt: 0)
        let page = CGRect(x: 0, y: 0, width: 595.2, height: 841.8)
        render.setValue(page, forKey: "paperRect")
        render.setValue(page, forKey: "printableRect")
        let data = NSMutableData()
        UIGraphicsBeginPDFContextToData(data, page, nil)
        render.prepare(forDrawingPages: NSMakeRange(0, render.numberOfPages))
        for i in 0..<render.numberOfPages {
            UIGraphicsBeginPDFPage()
            render.drawPage(at: i, in: UIGraphicsGetPDFContextBounds())
        }
        UIGraphicsEndPDFContext()
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
        data.write(to: url, atomically: true)
        return url
        #else
        let url = FileManager.default.temporaryDirectory.appendingPathComponent(filename)
        let data = html.data(using: .utf8) ?? Data()
        try? data.write(to: url)
        return url
        #endif
    }
}
